/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajopracticotsb;

import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author javier
 */
public class CargarArchivo extends javax.swing.JPanel {

    /**
     * Creates new form CargarArchivo
     */
    private DefaultListModel<String> model = new DefaultListModel();
    private MainPantalla ventanaPrincipal;
    public CargarArchivo(MainPantalla ventanaPrincipal) {
        initComponents();
        this.ventanaPrincipal = ventanaPrincipal;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        importar = new javax.swing.JButton();

        setBackground(new java.awt.Color(188, 181, 87));

        lista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "No hay Archivos" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lista);

        jButton1.setText("Nuevo Archivo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Quitar");

        importar.setText("Importar");
        importar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                        .addComponent(importar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(importar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       JFileChooser explorador = new JFileChooser();
       //Le cambiamos el titulo
       explorador.setDialogTitle("Seleccionar documento...");
       //Agregamos un filtro de extensiones
        explorador.setFileFilter(new FileNameExtensionFilter("TEXT FILES", "txt", "text"));
       //Muestro un dialogo sin pasarle parent con el boton de Seleccionar
        int seleccion = explorador.showDialog(null, "Seleccionar");
        //analizamos la respuesta
        
        switch(seleccion) {
case JFileChooser.APPROVE_OPTION:
    //Podemos crear un File con lo seleccionado
    File archivo = explorador.getSelectedFile();
    //y guardar una ruta
    String ruta = archivo.getPath();
    //Agregar a archivos a procesar
    model.addElement(ruta);
    lista.setModel(model);
    break;
    case JFileChooser.CANCEL_OPTION:
    //dio click en cancelar o cerro la ventana
    break;

case JFileChooser.ERROR_OPTION:
 //llega aqui si sucede un error
 break;
}
    }//GEN-LAST:event_jButton1MouseClicked

    private void importarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importarMouseClicked
        for (int i = 0; i < model.size(); i++) {
            ventanaPrincipal.tomarArchivo(model.get(i));
        }
        this.ventanaPrincipal.Procesar();
        this.model.clear();
    }//GEN-LAST:event_importarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton importar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lista;
    // End of variables declaration//GEN-END:variables
}
