/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajopracticotsb;


import Negocio.Gestor;
import java.awt.BorderLayout;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ProgressMonitor;


/**
 *
 * @author javier
 */
public class MainPantalla extends javax.swing.JFrame {

    /**
     * Creates new form MainPantalla
     */
    VocabularioGuardado panelVocabularioGuardadro;
    CargarArchivo panelCargarArchivo;
    public MainPantalla() {
        initComponents();
           this.setResizable(false);
         panelVocabularioGuardadro = new VocabularioGuardado(this);
        panelCargarArchivo = new CargarArchivo(this);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        panelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cargarArchivo = new javax.swing.JButton();
        mostrarVocabulario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelPrincipal.setBackground(java.awt.SystemColor.desktop);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        jPanel1.setBackground(java.awt.SystemColor.desktop);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cargarArchivo.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        cargarArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabajopracticotsb/181501-interface/png/document-2.png"))); // NOI18N
        cargarArchivo.setText("Cargar Archivo");
        cargarArchivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cargarArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargarArchivoMouseClicked(evt);
            }
        });
        jPanel1.add(cargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 424, -1));

        mostrarVocabulario.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        mostrarVocabulario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabajopracticotsb/181501-interface/png/list.png"))); // NOI18N
        mostrarVocabulario.setText("Vocabulario Guardado");
        mostrarVocabulario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrarVocabulario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarVocabularioMouseClicked(evt);
            }
        });
        jPanel1.add(mostrarVocabulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 0, 434, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarArchivoMouseClicked

         panelCargarArchivo.setSize(panelPrincipal.getWidth(),panelPrincipal.getHeight());
         panelCargarArchivo.setLocation(0, 0);
         panelPrincipal.removeAll();   
         panelPrincipal.add(panelCargarArchivo,BorderLayout.CENTER);
         panelPrincipal.revalidate();
         panelPrincipal.repaint();
       
    }//GEN-LAST:event_cargarArchivoMouseClicked

    private void mostrarVocabularioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarVocabularioMouseClicked
        
         panelVocabularioGuardadro.setSize(panelPrincipal.getWidth(),panelPrincipal.getHeight());
         panelVocabularioGuardadro.setLocation(0, 0);
         panelPrincipal.removeAll();   
         panelPrincipal.add(panelVocabularioGuardadro,BorderLayout.CENTER);
         panelPrincipal.revalidate();
         panelPrincipal.repaint();
         panelVocabularioGuardadro.cargarTabla((ArrayList)conocerVocabulario());
        
    }//GEN-LAST:event_mostrarVocabularioMouseClicked
    public  void tomarArchivo(String ruta){
       leector.TomarRuta(ruta);
    }
    public List conocerVocabulario(){
        return leector.ConsultarVocabulario();
    }
    ProgressMonitor progressMonitor = new ProgressMonitor(null,
                                  "Importando...",
                                  "", 0, 100);
    public void Procesar(){
        leector.execute();
        leector.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if ("progress".equals(evt.getPropertyName())) {
                    int progress = (Integer) evt.getNewValue();
                 progressMonitor.setProgress(progress);
                 String message =
                String.format("Completed %d%%.\n", progress);
            progressMonitor.setNote(message);
                
                }
            }
        });
        
    }
    public List vocabularioFiltrado(String tex){
        return leector.ConsultarPorFiltro(tex);
    }
    /**
     * @param args the command line arguments
     */
        private Gestor leector = new Gestor();
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPantalla().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargarArchivo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JButton mostrarVocabulario;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
